### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ynohtna92** [Karawasa/Element-TD#1]
To do list for ElementTD
- [x] Port UI from Scaleform -> Panorama 0c71e8fe55af9a6c2da3b24cd50c2dba5d5c73f8
- [x] Add-in Loading Screen 28016b639fdb42ecded80fb2fe012e92f074c9ec
- [x] Update building ghost system
- [x] Update Creep List 9c9ab1909f7d8e15dc2263719b91a0739834a51c & f62a7e02440503d57a5b646639fcbe7ab26d3a34
- [x] Update Tower Models d94bed570ef8b29bd2c4aa922f3d3a0cfd124001
- [x] Update Map
- [x] Update Tower Icons/Ability Icons a170e6e35f45d297005975709afca9d8d14c4134 & 2f530dd2b1629391a0c9e2c4718b021155602d26
- [x] Update Tower Particles
- [x] Update Tower Sounds
- [x] Update Tower Tooltips
- [x] Leaderboard System http://hatinacat.com/leaderboard

**Comment by ynohtna92** [comment]
Loading Screen completed with 28016b639fdb42ecded80fb2fe012e92f074c9ec

**Comment by MNoya** [comment]
Building ghost system almost finished with aba229ad278662fd39be34ef84945a5f168376b7

Need to review the way the abilities/items are added, and how the tower KVs are defined.

**Comment by MNoya** [comment]
Creep list up to date with 9c9ab1909f7d8e15dc2263719b91a0739834a51c & f62a7e02440503d57a5b646639fcbe7ab26d3a34

**Comment by MNoya** [comment]
Icons updated with a170e6e35f45d297005975709afca9d8d14c4134 & 2f530dd2b1629391a0c9e2c4718b021155602d26

**Comment by MNoya** [comment]
I think we should remove all tower sounds, it gets deafening/annoying after a while.

**Comment by ynohtna92** [comment]
Leaderboard system is in progress at http://hatinacat.com/leaderboard

**Comment by Karawasa** [comment]
Hmm I kind of dislike the silence. I noticed when playing that a lot of the time my game would go mute or close to it. I think we should make it so that sound is localized. In other words, you only hear sounds from what is on your screen or close to it. That way, all tower sounds can come back...the sound channel cap can be removed...because you're only hearing your own sounds (unless you scroll view over to someone else).

**Comment by ynohtna92** [comment]
Sounds should be localised. It is more a problem with the engine as even though your camera isn't near the sound source it will still use a channel. 

It is more to do with some creeps having footstep/dying/moving sounds that we have not removed yet.

**Comment by Karawasa** [comment]
Ok let's definitely remove all footstep and moving sounds. As for dying sounds, either we go all or nothing on that one. I'd prefer to keep creep death sounds but if they are eating into channels for tower sounds, then let's nuke them too.

**Comment by MNoya** [comment]
Alright sound is done and Leaderboard is well under way, we enter pre-release test mode this weekend.

**Comment by MNoya** [comment]
New tracking for final sprint at #100
